import Foundation

/// The Japanese translations, keyed by the English original.
///
/// One catalogue for both apps. Ablox and Ablox Studio share the design
/// system, the project store, the block vocabulary and every message the
/// networking layer produces, so splitting the table would mean deciding for
/// each string which half it belongs to — and getting that wrong shows up as a
/// screen in the wrong language. The handful of entries only one app uses cost
/// a few kilobytes and nothing else.
///
/// ## Rules for entries
///
/// - The key is the exact English string passed to `L(...)`.
/// - `{}` marks a value filled in at runtime. Both languages must have the
///   same number of them, and in an order that makes sense in that language —
///   `LocalizationTests` checks the count, not the order.
/// - Japanese UI text omits the trailing full stop that English sentences take
///   in prose, but keeps `。` in anything that reads as a sentence.
///
/// Stored as an array of pairs rather than a dictionary literal on purpose: a
/// repeated key in a dictionary literal is a *runtime* crash, and this table is
/// too long to trust to eyes. Built with `uniquingKeysWith`, so a duplicate is
/// a failing test instead of a crash on someone's iPad.
public enum Strings {

    public static let japanese: [String: String] =
        Dictionary(entries.map { ($0.0, $0.1) }, uniquingKeysWith: { first, _ in first })

    /// Exposed so the tests can see duplicates, which the dictionary hides.
    public static let entries: [(String, String)] =
        coreEntries + clientEntries + studioEntries + guideEntries + catalogueEntries + scriptEntries

    // MARK: - Shared vocabulary

    /// Block shapes, materials, behaviours, parts, sounds, and everything the
    /// networking and validation layers say. Used by both apps.
    static let coreEntries: [(String, String)] = [
        // Languages
        ("Match the iPad", "iPadに合わせる"),

        // BlockShape
        ("Box", "四角"),
        ("Sphere", "球"),
        ("Cylinder", "円柱"),
        ("Cone", "円すい"),
        ("Plane", "板"),

        // BlockMaterial
        ("Plastic", "プラスチック"),
        ("Metal", "金属"),
        ("Glass", "ガラス"),
        ("Neon", "ネオン"),
        ("Matte", "つや消し"),

        // BlockBehavior — displayName
        ("None", "なし"),
        ("Spawn Point", "スタート地点"),
        ("Checkpoint", "チェックポイント"),
        ("Hazard", "危険ブロック"),
        ("Collectible", "アイテム"),
        ("Goal", "ゴール"),
        ("Trigger", "トリガー"),
        ("Bouncy", "トランポリン"),
        ("Disappearing", "消えるゆか"),
        ("Teleporter", "ワープ"),

        // BlockBehavior — guidance
        ("Ordinary scenery. Players can stand on it and nothing else happens.",
         "ふつうのブロック。乗れるだけで、ほかには何も起きません。"),
        ("Players start on top of this block.",
         "プレイヤーはこのブロックの上からスタートします。"),
        ("Touching it sets where the player respawns. Players walk through it.",
         "さわると復活地点がここになります。すり抜けられます。"),
        ("Touching it sends the player back to their last checkpoint.",
         "さわると直前のチェックポイントまで戻されます。"),
        ("Each player can collect it once. Players walk through it.",
         "ひとり1回だけ取れます。すり抜けられます。"),
        ("Touching it ends the round for everyone.",
         "さわると全員のラウンドが終わります。"),
        ("Does nothing by itself — add a rule that listens for it.",
         "これ単体では何も起きません。ルールを足して使います。"),
        ("Launches anyone who lands on it. A trampoline.",
         "乗った人を上に打ち上げます。トランポリンです。"),
        ("Vanishes shortly after it is stepped on, then comes back.",
         "踏まれてすぐ消えて、しばらくすると戻ってきます。"),
        ("Moves the player to another block. Players walk through it.",
         "プレイヤーを別のブロックへ移動させます。すり抜けられます。"),

        // PresetKind — displayName
        ("Block", "ブロック"),
        ("Platform", "足場"),
        ("Pillar", "柱"),
        ("Ramp", "坂"),
        ("Orb", "コイン"),
        ("Lava", "溶岩"),
        ("Spawn", "スタート"),

        // PresetKind — guidance
        ("A plain 2×1×2 box. The everyday building material.",
         "ふつうの2×1×2の箱。いちばんよく使う材料です。"),
        ("A wide, thin 6×0.5×6 slab. Floors and floating islands.",
         "広くて薄い6×0.5×6の板。床や浮島に。"),
        ("A tall thin cylinder, 4 high. Posts, columns, poles.",
         "高さ4の細い円柱。柱や棒に。"),
        ("A long box already tilted 25°, so players can walk up it.",
         "最初から25°傾いた細長い箱。そのまま登れます。"),
        ("A glowing yellow sphere worth 10 points, collectible once per player.",
         "光る黄色い球。10ポイントで、ひとり1回だけ取れます。"),
        ("A flat slab of lava. Touching it sends players back to their checkpoint.",
         "平たい溶岩。さわるとチェックポイントまで戻されます。"),
        ("A green pad that saves where a player respawns.",
         "復活地点を記録する緑のパッド。"),
        ("A purple glass gate. Touching it ends the round.",
         "紫のガラスのゲート。さわるとラウンドが終わります。"),
        ("A cyan pad players start on. Every world needs at least one.",
         "プレイヤーがスタートする水色のパッド。ワールドに最低1つ必要です。"),

        // SoundCue
        ("Collect", "アイテム取得"),
        ("Checkpoint reached", "チェックポイント"),
        ("Hurt", "ダメージ"),
        ("Bounce", "バウンド"),
        ("Teleport", "ワープ"),
        // SoundCue's "Goal" is the same word as BlockBehavior's and is
        // translated once, above — a second row here would be a duplicate key.
        ("Player joined", "参加"),
        ("Player left", "退出"),
        ("Tick", "カチッ"),
        ("Error", "エラー"),

        // DisconnectReason
        ("You left the world.", "ワールドから出ました。"),
        ("The host closed the world.", "ホストがワールドを閉じました。"),
        ("Could not connect — check the room code is the same on both iPads.",
         "接続できませんでした。両方のiPadで部屋コードが同じか確認してください。"),
        ("That iPad is running a different version of Ablox. Update both to play together.",
         "そのiPadのAbloxはバージョンが違います。一緒に遊ぶには両方を更新してください。"),
        ("That world is full.", "そのワールドは満員です。"),
        ("Lost connection to the host.", "ホストとの接続が切れました。"),
        ("The host stopped responding.", "ホストが応答しなくなりました。"),
        ("Disconnected.", "切断されました。"),
        ("Reconnecting…", "再接続しています…"),
        ("Reconnecting… ({} of {})", "再接続しています…（{}/{}）"),

        // Editor tools
        ("Select", "選択"),
        ("Move", "移動"),
        ("Rotate", "回転"),
        ("Scale", "拡大縮小"),

        // Validation
        ("{} points at a parent that no longer exists.", "{} の親ブロックがもう存在しません。"),
        ("{} has a zero scale component and will be invisible.", "{} は大きさが0の軸があり、見えなくなります。"),
        ("{} is part of a parent cycle.", "{} は親子関係が循環しています。"),
        ("Rule “{}” refers to a block that no longer exists.",
         "ルール「{}」が、もう存在しないブロックを指しています。"),
        ("No spawn point — players will start above the origin.",
         "スタート地点がありません。プレイヤーは原点の上から始まります。"),

        // Shared between both apps' lobbies
        ("Cancel", "キャンセル"),
        ("Create", "作成"),
        ("Delete", "削除"),
        ("Duplicate", "複製"),
        ("Done", "完了"),
        ("Join", "参加"),
        ("Name", "名前"),
        ("OK", "OK"),
        ("Off", "オフ"),
        ("Room code", "部屋コード"),
        ("Start from", "テンプレート"),
        ("My World", "マイワールド"),
        ("Update needed", "更新が必要"),
        ("Build together", "みんなで作る"),
        ("Encrypted", "暗号化"),
        ("Full", "満員"),
        ("Host", "ホスト"),
        ("Part", "パーツ"),
        ("Player", "プレイヤー"),
        ("World", "ワールド"),
        ("{} · {}", "{}・{}"),

        // Project templates
        ("Obstacle Course", "アスレチック"),
        ("Blank", "空のワールド"),
        ("A floor, a spawn pad, stairs, a coin and a finish line. Tap Play and it already works.",
         "床・スタート地点・階段・コイン・ゴールつき。そのまま遊べます。"),
        ("Just a floor and a spawn point. Build from nothing.",
         "床とスタート地点だけ。ゼロから作ります。"),
    ]

    // MARK: - Ablox (the player client)

    static let clientEntries: [(String, String)] = [
        // Saved data, backups, earlier versions, recently deleted
        ("A backup file holds your avatar, coins, saved games and worlds. Keep it in Files or send it to another iPad, then open it there with “Restore from a backup”.", "バックアップファイルには、アバター・コイン・ゲームのセーブ・ワールドが入ります。「ファイル」に取っておくか別のiPadに送って、そこで「バックアップから戻す」で開きます。"),
        ("A version is kept every few minutes while you build. Going back keeps the current one as a version too, so you can change your mind.", "作っている間、数分ごとに版が保存されます。もどしても今の状態が版として残るので、やっぱりやめることもできます。"),
        ("Could not save this game's progress: {}", "このゲームの進みぐあいを保存できませんでした: {}"),
        ("Delete all saved games", "ゲームのセーブをすべて消す"),
        ("Delete every saved game?", "すべてのゲームのセーブを消しますか？"),
        ("Delete now", "今すぐ消す"),
        ("Delete these worlds for good?", "これらのワールドを完全に消しますか？"),
        ("Delete this saved game?", "このゲームのセーブを消しますか？"),
        ("Deleted worlds stay here for 30 days, then go for good.", "消したワールドは30日間ここに残り、そのあと完全に消えます。"),
        ("Earlier versions", "以前の版"),
        ("Earlier versions of “{}”", "「{}」の以前の版"),
        ("Empty", "空にする"),
        ("Every game starts again from nothing. Worlds and coins are not touched.", "どのゲームも最初からになります。ワールドとコインはそのままです。"),
        ("Games keep your progress — coins, quests, what you unlocked — on this iPad by themselves, even in a friend's room. It comes back next time you play the same game.", "ゲームの進みぐあい（コイン・クエスト・解放したもの）は、友だちの部屋で遊んでいても、このiPadに自動で保存されます。次に同じゲームで遊ぶとつづきから始まります。"),
        ("Go back", "もどす"),
        ("Go back to this", "この版にもどす"),
        ("Go back to this version?", "この版にもどしますか？"),
        ("Make a backup", "バックアップを作る"),
        ("No earlier versions yet", "以前の版はまだありません"),
        ("No game has saved anything yet.", "まだどのゲームもセーブしていません。"),
        ("Nothing deleted", "消したワールドはありません"),
        ("Put back", "もとにもどす"),
        ("Recently deleted", "最近消したもの"),
        ("Restore from a backup", "バックアップから戻す"),
        ("Restored: {} saved games and {} worlds.", "戻しました: ゲームのセーブ {} 個、ワールド {} 個。"),
        ("Save it to Files, or AirDrop it to the iPad you are moving to.", "「ファイル」に保存するか、引っこし先のiPadにAirDropで送ってください。"),
        ("Saved data", "保存データ"),
        ("That backup was made by a newer Ablox. Update this iPad first.", "このバックアップは新しいAbloxで作られています。先にこのiPadのAbloxを更新してください。"),
        ("That file could not be read: {}", "そのファイルを読めませんでした: {}"),
        ("That file is not an Ablox backup.", "そのファイルはAbloxのバックアップではありません。"),
        ("That file is too big to be an Ablox backup.", "Abloxのバックアップにしては大きすぎるファイルです。"),
        ("The backup could not be written: {}", "バックアップを書き出せませんでした: {}"),
        ("The world as it is now is kept, so this can be undone.", "今のワールドも残るので、あとで取り消せます。"),
        ("They appear once the world has been saved a few times.", "ワールドが何回か保存されると、ここに出てきます。"),
        ("This cannot be undone.", "元にはもどせません。"),
        ("Worlds you delete wait here for 30 days.", "消したワールドは30日間ここで待っています。"),
        ("Your progress in “{}” will start again from nothing.", "「{}」の進みぐあいが最初からになります。"),
        ("{} days left", "のこり {} 日"),
        ("“{}” moves to Recently Deleted, where it can be put back for 30 days.", "「{}」は「最近消したもの」に移ります。30日間はもとにもどせます。"),
        // Main menu and lobbies
        ("Worlds", "ワールド"),
        ("Play", "プレイ"),
        ("Settings", "設定"),
        ("Shop", "ショップ"),
        ("Avatar", "アバター"),
        ("New world", "新しいワールド"),
        ("Rename world", "名前を変更"),
        ("Rename", "変更"),
        ("Delete this world?", "このワールドを削除しますか？"),
        ("“{}” will be gone for good.", "「{}」は完全に消えます。"),
        ("Play them solo, or host one and let friends join from the Play tab.",
         "ひとりで遊ぶことも、ホストして友だちをプレイタブから招くこともできます。"),

        // Play lobby
        ("Play on your own", "ひとりで遊ぶ"),
        ("Join a friend's world", "友だちのワールドに参加"),
        ("Join world", "ワールドに参加"),
        ("Nearby worlds", "近くのワールド"),
        ("NEARBY MULTIPLAYER", "近くのマルチプレイ"),
        ("Can't search for iPads", "近くのiPadを探せません"),
        ("Could not join", "参加できませんでした"),
        ("Hosted by {}", "ホスト: {}"),
        ("The host's iPad shows this code.", "ホストのiPadに表示されているコードです。"),
        ("Hosts appear here automatically. Public rooms open with one tap; a private room needs the code its host shows you. Either way the connection is encrypted.",
         "ホストはここに自動で出てきます。パブリックの部屋はタップするだけで参加、プライベートの部屋はホストの画面に出ているコードが必要です。どちらも通信は暗号化されます。"),
        ("Enter code", "コードを入力"),
        ("Public", "パブリック"),
        ("Private", "プライベート"),
        ("Who can join?", "だれが参加できる？"),
        ("Public — anyone nearby can join", "パブリック — 近くのだれでも参加できる"),
        ("Private — only people with the room code", "プライベート — 部屋コードを知っている人だけ"),
        ("You can switch this any time from the room code at the top of the screen.", "あとから画面の上の部屋コードをタップして切りかえられます。"),
        ("PUBLIC ROOM", "パブリック"),
        ("PRIVATE ROOM", "プライベート"),

        // In game
        ("Players", "プレイヤー"),
        ("Scoreboard", "スコア"),
        ("Connecting…", "接続しています…"),
        ("Looking for the world…", "ワールドを探しています…"),
        ("TLS 1.3 local mesh", "TLS 1.3 ローカル接続"),
        ("Discovery paused", "検出を停止中"),
        ("Searching for nearby iPads over Bonjour.", "Bonjourで近くのiPadを探しています。"),
        ("iPad Edition", "iPad版"),
        ("Worn", "着用中"),
        ("Tap to wear", "タップで着る"),
        ("Chat", "チャット"),
        ("Say something…", "メッセージを入力…"),
        ("Just you so far.", "まだあなただけです。"),
        ("ROOM CODE", "部屋コード"),
        ("Room code {}", "部屋コード {}"),
        ("Leave world", "ワールドから出る"),
        ("Leave", "出る"),
        ("Back to menu", "メニューに戻る"),
        ("Disconnected", "切断"),
        ("Unmute everyone ({})", "全員のミュートを解除（{}）"),
        ("{}ms", "{}ms"),

        // Controls
        ("Jump", "ジャンプ"),
        ("Camera", "カメラ"),
        ("Movement stick", "移動スティック"),

        // Avatar customiser
        ("Display name", "表示名"),
        ("Colours", "色"),
        ("Hat", "ぼうし"),
        ("Height", "身長"),
        ("Surprise me", "おまかせ"),
        ("This is how you appear in everyone else's world.",
         "ほかの人のワールドでは、この見た目で表示されます。"),

        // Shop
        ("Category", "カテゴリ"),
        ("Yours", "所持中"),
        ("To unlock", "未所持"),
        ("coins", "コイン"),
        ("earned all time", "これまでの合計"),
        ("Earn coins by collecting and finishing rounds, then unlock new colours and hats.",
         "アイテムを集めたりラウンドをクリアするとコインが貯まり、新しい色やぼうしと交換できます。"),

        // Settings
        ("Controls", "操作"),
        ("Movement", "移動"),
        ("Network", "ネットワーク"),
        ("About", "このアプリについて"),
        ("Language", "言語"),
        ("Sound effects", "効果音"),
        ("Haptics", "触覚フィードバック"),
        ("Joystick on the right", "スティックを右側に"),
        ("Invert camera up/down", "カメラの上下を反転"),
        ("Camera sensitivity", "カメラ感度"),
        ("Reset", "リセット"),
        ("Controls, feel, and what Ablox is doing on your network.",
         "操作・感触と、Abloxがネットワークで行っていることの説明です。"),
        ("These change how your own avatar feels. The world's own gravity still applies to blocks.",
         "自分のアバターの操作感だけが変わります。ブロックにはワールド側の重力がそのまま効きます。"),
        ("Ablox is a sandbox you build and play with friends in the same room. Build worlds in Ablox Studio, then host them here.",
         "Abloxは、同じ部屋にいる友だちと作って遊ぶサンドボックスです。Ablox Studioでワールドを作り、ここでホストします。"),
        ("Made with SwiftUI, RealityKit and Network.framework. No third-party code.",
         "SwiftUI・RealityKit・Network.frameworkで作られています。外部ライブラリは使っていません。"),
        ("Ablox Studio has the same setting.", "Ablox Studioにも同じ設定があります。"),
        ("Swaps the stick and the camera area. For left-handed players.",
         "スティックとカメラ領域を入れ替えます。左利きの人向けです。"),
        ("Drag down to look up.", "下にドラッグすると上を向きます。"),
        ("How far the view turns for one swipe.", "1回のスワイプで視点がどれだけ回るか。"),
        ("A tap when you collect something or hit a checkpoint.",
         "アイテムを取ったときやチェックポイントに着いたときに振動します。"),
        ("Service", "サービス"),
        ("Transport", "通信"),
        ("Discovery", "検出"),
        ("Protocol version", "プロトコル版数"),
        ("This iPad", "このiPad"),
        ("TCP over TLS 1.3, pre-shared key", "TCP + TLS 1.3（事前共有鍵）"),
        ("Bonjour, plus direct peer-to-peer", "Bonjourと直接ピアツーピア"),
        ("Play traffic never touches a server. Worlds and player positions travel directly between iPads on your local network, encrypted with a key derived from the room code the host shows you. Anyone who knows that code can join and can read that session's traffic, so share it only with the people you want in the world. There are two exceptions, and both only read from public GitHub repositories: the Games tab downloads published worlds, and a world set to get its scripts from GitHub fetches them when you host it. Nothing about you is sent.",
         "プレイ中の通信はサーバーを経由しません。ワールドやプレイヤーの位置は、ローカルネットワーク上のiPad間を直接やりとりされ、ホストが表示する部屋コードから作った鍵で暗号化されます。そのコードを知っている人は誰でも参加でき、そのセッションの通信を読めます。ワールドに入れたい相手にだけ伝えてください。例外は2つで、どちらもGitHubの公開リポジトリを読むだけです。「ゲーム」タブは公開されたワールドをダウンロードし、スクリプトをGitHubから取得するよう設定されたワールドは、ホストするときにスクリプトを取得します。あなたに関する情報は一切送信されません。"),

        // Controls help
        ("Drag to walk. Push all the way to run.", "ドラッグで歩きます。いっぱいまで倒すと走ります。"),
        ("Drag to look around.", "ドラッグで見回します。"),

        // Avatar and shop items
        ("Cap", "キャップ"),
        ("Crown", "王冠"),
        ("Antenna", "アンテナ"),
        ("Halo", "天使の輪"),
        ("Body", "からだ"),
        ("Head & arms", "頭と腕"),
        ("Legs & hat", "脚とぼうし"),
        ("{}, owned", "{}（所持中）"),
        ("{}, {} coins", "{}、{}コイン"),
        ("Coral", "コーラル"),
        ("Amber", "アンバー"),
        ("Sun", "サン"),
        ("Mint", "ミント"),
        ("Cyan", "シアン"),
        ("Blue", "ブルー"),
        ("Violet", "バイオレット"),
        ("Pink", "ピンク"),
        ("Chalk", "チョーク"),
        ("Concrete", "コンクリート"),
        ("Slate", "スレート"),
        ("Graphite", "グラファイト"),
        ("“{}” will be removed from this iPad. This cannot be undone.",
         "「{}」はこのiPadから削除されます。元に戻せません。"),
    ]

    // MARK: - Ablox Studio

    static let studioEntries: [(String, String)] = [
        // Project browser
        ("Your projects", "プロジェクト"),
        ("STUDIO · Build 3D worlds on iPad", "STUDIO・iPadで3Dワールドを作る"),
        ("New project", "新しいプロジェクト"),
        ("Delete this project?", "このプロジェクトを削除しますか？"),
        ("Join and edit together", "参加して一緒に編集"),
        ("Shared by {}", "共有元: {}"),

        // Toolbar
        ("Back to projects", "プロジェクト一覧に戻る"),
        ("Unsaved changes", "未保存の変更"),
        ("Grid", "グリッド"),
        ("Angle", "角度"),
        ("Grid snapping", "グリッドスナップ"),
        ("Angle snapping", "角度スナップ"),
        ("Undo", "取り消す"),
        ("Redo", "やり直す"),
        ("Frame selection", "選択に寄る"),
        ("How to make a map", "マップの作り方"),
        ("Share this project", "このプロジェクトを共有"),
        ("Sharing this project", "共有中"),
        ("Stop sharing", "共有をやめる"),
        ("Stop", "停止"),
        ("{} editing", "{}人が編集中"),
        ("Encrypted with TLS 1.3", "TLS 1.3で暗号化"),
        ("Other iPads running Ablox Studio can find this project and edit it with you. Give them the code.",
         "Ablox Studioを開いているほかのiPadが、このプロジェクトを見つけて一緒に編集できます。このコードを伝えてください。"),
        ("Sharing — room code {}", "共有中 — 部屋コード {}"),
        ("Joined {}", "{} に参加しました"),
        ("Saved", "保存しました"),
        ("Testing — tap Stop to keep building", "テスト中 — 停止を押すと編集に戻ります"),

        // Explorer
        ("Explorer", "エクスプローラ"),
        ("Find a part", "パーツを検索"),
        ("Move to top level", "最上位に移動"),
        ("Hide", "非表示"),
        ("Show", "表示"),
        ("No problems", "問題なし"),
        ("+{} more", "ほか{}件"),

        // Inspector
        ("Appearance", "見た目"),
        ("Transform", "位置・大きさ"),
        ("Physics", "物理"),
        ("Behaviour", "ふるまい"),
        ("Acts as", "種類"),
        ("Actions", "操作"),
        ("Shape", "形"),
        ("Material", "素材"),
        ("Colour", "色"),
        ("Colour all", "まとめて色を変える"),
        ("Nudge all", "まとめて動かす"),
        ("Delete all", "すべて削除"),
        ("Tags", "タグ"),
        ("coin, trap, door…", "coin, trap, door…"),
        ("A rule can listen for any block with a tag, so one rule can cover a whole group.",
         "ルールはタグでまとめて反応できるので、1つのルールでグループ全体を扱えます。"),
        ("Anchored", "固定"),
        ("Solid", "当たり判定"),
        ("Visible", "表示"),
        ("Stays put. Turn off to let it fall in Play mode.",
         "その場に固定します。オフにするとプレイ中に落ちます。"),
        ("Players can walk through it when off.", "オフにするとすり抜けられます。"),
        ("Score", "スコア"),
        ("Points", "ポイント"),
        ("Penalty", "ペナルティ"),
        ("Launch speed", "打ち上げの強さ"),
        ("Delay before it goes", "消えるまでの時間"),
        ("Time until it returns", "戻るまでの時間"),
        ("Wait between uses", "次に使えるまでの時間"),
        ("Sends you to", "移動先"),
        ("Nowhere", "なし"),
        ("Target", "移動先"),
        ("World name", "ワールド名"),
        ("Ground", "地面"),
        ("Lighting", "ライト"),
        ("Show backdrop", "背景を表示"),
        ("Gravity", "重力"),
        ("Fall limit", "落下限界"),
        ("Brightness", "明るさ"),
        ("Sun direction", "太陽の向き"),
        ("Sun height", "太陽の高さ"),
        ("Falls under gravity in Play mode", "プレイ中に重力で落ちます"),
        ("Unknown sound — nothing will play", "不明な音です。何も鳴りません"),
        ("Making a map", "マップの作り方"),
        ("A player who falls below the fall limit respawns.",
         "落下限界より下に落ちたプレイヤーは復活します。"),

        // Rules
        ("Rules", "ルール"),
        ("Add rule", "ルールを追加"),
        ("Delete rule", "ルールを削除"),
        ("Rule name", "ルール名"),
        ("When", "きっかけ"),
        ("Then", "すること"),
        ("Add action", "動作を追加"),
        ("Only once", "1回だけ"),
        ("Limits", "制限"),
        ("Sound", "音"),
        ("(deleted)", "（削除済み）"),
        ("tag", "タグ"),
        ("Within", "半径"),
        ("Every", "間隔"),

        // Triggers
        ("A player touches a block", "プレイヤーがブロックにさわったとき"),
        ("A player touches any tagged block", "プレイヤーがタグ付きブロックにさわったとき"),
        ("A player taps a block", "プレイヤーがブロックをタップしたとき"),
        ("A player comes close", "プレイヤーが近づいたとき"),
        ("The round starts", "ラウンドが始まったとき"),
        ("On a timer", "一定時間ごと"),
        ("A score is reached", "スコアに達したとき"),

        // Actions
        ("Change a block's colour", "ブロックの色を変える"),
        ("Move a block", "ブロックを動かす"),
        ("Hide a block", "ブロックを隠す"),
        ("Make a block walk-through", "ブロックをすり抜けられるようにする"),
        ("Teleport the player", "プレイヤーをワープさせる"),
        ("Award points", "ポイントを与える"),
        ("Show a message", "メッセージを表示する"),
        ("Play a sound", "音を鳴らす"),
        ("End the round", "ラウンドを終わらせる"),

        // Editor viewport
        ("Add {}", "{}を追加"),
        // Bare "Undo"/"Redo" are in the toolbar section above; these are the
        // forms that name the action being undone.
        ("Undo {}", "取り消す: {}"),
        ("Redo {}", "やり直す: {}"),
        ("Panel", "パネル"),
    ]

    // MARK: - Studio's map-making guide
    //
    // Long-form prose, kept apart from the interface strings so a translator
    // can work through it in one pass. Shown by `MapGuideSheet` and written to
    // `docs/making-maps.ja.md`.

    static let guideEntries: [(String, String)] = [
        ("# Making a map in Ablox Studio", "# Ablox Studioでマップを作る"),
        ("Studio shows this same guide in the app — the ? button in the toolbar.",
         "このガイドはアプリ内でも読めます。ツールバーの「?」ボタンです。"),
        ("Ten steps from an empty grid to something people can play. Tap a heading to open it.",
         "何もないグリッドから、人が遊べるものになるまでの10ステップ。見出しをタップすると開きます。"),

        // 1. Start a world
        ("Start a world", "ワールドを作る"),
        ("Every map is one world file. Studio keeps them for you and saves as you work.",
         "マップ1つがワールドファイル1つです。Studioが保管し、作業中に自動で保存します。"),
        ("From the project list, tap the new-project button, name the world, and pick a template.",
         "プロジェクト一覧で新規ボタンを押し、名前を付けてテンプレートを選びます。"),
        ("Obstacle Course starts you with a floor, a spawn pad, stairs, a coin and a finish line — it already works if you press Play. Blank gives you a floor and a spawn point.",
         "「アスレチック」は床・スタート地点・階段・コイン・ゴールが最初から入っていて、プレイを押せばもう遊べます。「空のワールド」は床とスタート地点だけです。"),
        ("Starting from Obstacle Course and taking things away is usually faster than starting from Blank, because the pieces are already wired up for you to copy.",
         "たいていは「アスレチック」から要らないものを消すほうが速く進みます。部品がすでに組み上がっていて、コピーして使えるからです。"),
        ("Build on the grid you land on. It is the floor, and it is not a block — you cannot select or delete it.",
         "最初に表示されるグリッドの上に作ります。これは床であってブロックではないので、選択も削除もできません。"),
        ("There is no Save button. Studio saves shortly after you stop editing, when you press Play, and when you go back to the project list.",
         "保存ボタンはありません。編集の手が止まった少しあと、プレイを押したとき、プロジェクト一覧に戻ったときに保存されます。"),
        ("The dot beside the world's name in the toolbar means there are changes not yet written. Saving is delayed on purpose: dragging a part makes an edit every frame, and writing all of them to storage would wear it out for no benefit.",
         "ツールバーのワールド名の横にある点は、まだ保存されていない変更があるという意味です。保存を遅らせているのはわざとで、パーツをドラッグすると毎フレーム編集が発生するため、その全部を書き込むとストレージを無駄に消耗させてしまうからです。"),

        // 2. Put parts in
        ("Put parts in", "パーツを置く"),
        ("The palette along the bottom of the viewport is where every part comes from.",
         "画面下のパレットが、すべてのパーツの出どころです。"),
        ("Tap a part in the palette and it lands in front of the camera.",
         "パレットのパーツをタップすると、カメラの前に置かれます。"),
        ("It is placed where you are looking at the moment you tap, not at the world origin — so aim first, then tap.",
         "置かれるのはタップした瞬間に見ている場所で、原点ではありません。先に向きを合わせてからタップします。"),
        ("The new part is selected straight away, so the Inspector on the right is already showing it.",
         "置いたパーツはすぐ選択状態になるので、右のインスペクタにそのまま表示されます。"),
        ("Tap the chevron above the palette to fold it away when you need the room.",
         "画面を広く使いたいときは、パレット上の矢印でたたむことができます。"),
        ("Parts land on the grid, so two of the same kind placed side by side line up exactly.",
         "パーツはグリッドに吸着するので、同じものを隣に置くとぴったり揃います。"),

        // 3. Move, turn, resize
        ("Move, turn, resize", "動かす・回す・大きさを変える"),
        ("Four tools in the toolbar. Pick one, then drag the part.",
         "ツールバーに4つのツールがあります。選んでからパーツをドラッグします。"),
        ("Select picks parts. Tap a part to select it; tap with two fingers to add it to the selection instead of replacing it.",
         "「選択」はパーツを選ぶツールです。タップで選択、2本指でタップすると選択に追加します（置き換えではありません）。"),
        ("Nothing is selectable in Play mode — the editing gestures are switched off there entirely.",
         "プレイ中は何も選択できません。編集用の操作がすべて無効になります。"),
        ("Move, Rotate and Scale each drag the selected parts along the ground or around their centre.",
         "「移動」「回転」「拡大縮小」は、選んだパーツを地面に沿って、または中心まわりに動かします。"),
        ("The grid button snaps position to 0.25, 0.5, 1 or 2 metres. The angle button snaps rotation to 15°, 45° or 90°. Both have an Off setting.",
         "グリッドボタンは位置を0.25・0.5・1・2メートルに吸着させます。角度ボタンは回転を15°・45°・90°に吸着させます。どちらもオフにできます。"),
        ("Off is for fine adjustment only — platforms that do not line up on the grid leave gaps a player can fall through.",
         "オフは微調整のときだけにします。グリッドに揃っていない足場は、プレイヤーが落ちる隙間を作ります。"),
        ("Undo and Redo go back through everything, including deletes.",
         "取り消しとやり直しは、削除を含めてすべての操作をさかのぼれます。"),
        ("Duplicate and Delete are in the Inspector's Actions group, and in the menu you get by pressing and holding a row in the Explorer list.",
         "複製と削除はインスペクタの「操作」にあります。エクスプローラの行を長押しして出るメニューからも使えます。"),
        ("Duplicating a group copies its children and keeps their internal parent links, so copying a whole staircase gives you a staircase, not nine loose steps.",
         "グループを複製すると子も一緒にコピーされ、親子関係も保たれます。階段をまるごとコピーすれば階段になり、バラバラの段が9個になることはありません。"),
        ("In the Explorer, drag one row onto another to make it a child. Moving the parent then moves the child with it.",
         "エクスプローラで行を別の行にドラッグすると、子にできます。親を動かすと子もついてきます。"),
        ("Group the parts you will want to copy or move as a unit before you build the second one — that is what turns one staircase into a tower.",
         "まとめてコピーしたり動かしたりするパーツは、2つめを作る前にグループにしておきます。これが階段1つを塔に変えるコツです。"),

        // 4. Make it look right
        ("Make it look right", "見た目を整える"),
        ("The Inspector on the right edits whatever is selected.",
         "右のインスペクタは、選択中のものを編集します。"),
        ("Name each part as you go. The Explorer list and every rule refer to parts by name.",
         "作りながらパーツに名前を付けます。エクスプローラもルールも、パーツを名前で指します。"),
        ("Colour and material change how a part is lit. Neon glows without needing a light; glass is see-through.",
         "色と素材で光り方が変わります。ネオンはライトがなくても光り、ガラスは透けます。"),
        ("Anchored keeps a part still. Turn it off and the part falls in Play mode.",
         "「固定」はパーツをその場に留めます。オフにするとプレイ中に落ちます。"),
        ("Almost everything you build should stay anchored. Unanchored parts are for the one crate you meant to knock over.",
         "作るものはほぼすべて固定のままにします。固定を外すのは「倒したい木箱1つ」のような場面だけです。"),
        ("Solid is what players collide with. Turn it off to walk through a part.",
         "「当たり判定」はプレイヤーがぶつかるかどうかです。オフにするとすり抜けられます。"),
        ("A part can be visible and not solid — that is how you make decoration players do not bump into.",
         "見えていて当たり判定がない、という状態も作れます。ぶつからない飾りはこうして作ります。"),

        // 5. Give parts a job
        ("Give parts a job", "パーツに役割を持たせる"),
        ("Behaviour is the no-code half of Ablox: pick one and the part does something when a player touches it.",
         "「ふるまい」はAbloxのノーコード部分です。選ぶだけで、プレイヤーがさわったときに何かが起きます。"),
        ("{} — {}", "{} — {}"),

        // 6. Tune the gimmicks
        ("Tune the gimmicks", "ギミックを調整する"),
        ("Bouncy, Disappearing and Teleporter each get their own settings under the behaviour picker.",
         "トランポリン・消えるゆか・ワープには、ふるまいの選択欄の下にそれぞれ専用の設定が出ます。"),
        ("Bouncy: launch speed, in metres per second, from 6 to 30. It starts at 14.",
         "トランポリン: 打ち上げの強さ（メートル毎秒）。6〜30で、初期値は14です。"),
        ("Speed replaces upward motion rather than adding to it, so bouncing while already rising cannot compound into an escape from the map.",
         "上向きの速度は加算ではなく置き換えです。上昇中にもう一度跳ねても速度が積み重ならないので、マップの外まで飛んでいくことはありません。"),
        ("Disappearing: how long before it goes, and how long until it comes back.",
         "消えるゆか: 消えるまでの時間と、戻ってくるまでの時間。"),
        ("Teleporter: the part it sends players to. A pad cannot target itself.",
         "ワープ: 飛ばす先のパーツ。自分自身は指定できません。"),
        ("Two pads pointing at each other make a two-way door. Pointing a pad at itself would drop the player back on the pad forever, so Studio does not offer it.",
         "2つのパッドを互いに向けると双方向の扉になります。自分自身を指すとプレイヤーが永久に同じパッドに戻り続けるので、Studioは選択肢に出しません。"),
        ("All three share a cooldown: the wait before the same part can fire again.",
         "3つとも共通で「次に使えるまでの時間」を持ちます。同じパーツがもう一度作動するまでの待ち時間です。"),
        ("The cooldown is per part and per player. It exists because a player standing on a bounce pad would otherwise be launched every single frame.",
         "この待ち時間はパーツごと・プレイヤーごとです。これがないと、トランポリンの上に立っているだけで毎フレーム打ち上げられてしまいます。"),

        // 7. Add rules
        ("Add rules", "ルールを足す"),
        ("When behaviours are not enough, the Rules tab on the left builds \"when this happens, do that\".",
         "ふるまいだけで足りないときは、左の「ルール」タブで「これが起きたら、こうする」を組み立てます。"),
        ("A rule is one trigger and any number of actions. Add a rule, pick the trigger, then add actions to it.",
         "ルールは、きっかけ1つと動作いくつかの組です。ルールを追加し、きっかけを選び、動作を足していきます。"),
        ("Triggers include touching or tapping a part, walking near one, the world starting, a repeating timer, and a score being reached.",
         "きっかけには、パーツにさわる・タップする・近づく、ワールドの開始、一定時間ごと、スコア到達があります。"),
        ("Actions can recolour or move a part, hide it, make it walk-through, teleport the player, award points, show a message, play a sound, or end the round.",
         "動作では、パーツの色を変える・動かす・隠す・すり抜けられるようにする、プレイヤーをワープさせる、ポイントを与える、メッセージを出す、音を鳴らす、ラウンドを終わらせる、ができます。"),
        ("Give a part the Trigger behaviour when you want it to do nothing on its own and only feed a rule.",
         "単体では何もせず、ルールのきっかけとしてだけ使いたいパーツには「トリガー」を設定します。"),
        ("The host decides what a rule does, not the player's iPad. That is why nobody can give themselves points by editing their own copy.",
         "ルールの結果を決めるのはホストで、プレイヤーのiPadではありません。だから手元のコピーを書き換えて自分にポイントを足す、ということはできません。"),

        // 8. Play it
        ("Play it", "遊んでみる"),
        ("The Play button swaps the editor for the game, in the same world, without leaving Studio.",
         "プレイボタンを押すと、Studioを出ないまま同じワールドがゲームに切り替わります。"),
        ("Press Play to drop in as a character. Press Stop to go back to editing.",
         "プレイを押すとキャラクターとして入り、停止を押すと編集に戻ります。"),
        ("Entering Play saves the world first, so a crash while testing cannot cost you the session's work.",
         "プレイに入る前に保存されるので、テスト中に落ちてもその日の作業は失われません。"),
        ("Play from the start every time you add a jump. A gap that looks crossable often is not.",
         "ジャンプを足したら毎回、最初から通して遊んでみます。越えられそうに見える隙間が、実は越えられないことはよくあります。"),
        ("The editing gestures are switched off in Play mode, so nothing you do as a player can move a part.",
         "プレイ中は編集操作が無効なので、プレイヤーとして何をしてもパーツは動きません。"),
        ("Watch where you land after touching a hazard — that tells you which checkpoint was actually the last one.",
         "危険ブロックにさわったあと、どこに戻されるかを見ます。実際に最後のチェックポイントがどれだったかが分かります。"),

        // 9. Build together
        ("Two iPads on the same Wi-Fi can edit one world at the same time.",
         "同じWi-Fiにいる2台のiPadで、1つのワールドを同時に編集できます。"),
        ("Tap Share. Studio shows a room code and starts advertising on the local network.",
         "共有ボタンを押すと、部屋コードが表示され、ローカルネットワークへの告知が始まります。"),
        ("On the other iPad, find the session in the list and enter the same code.",
         "もう一方のiPadで一覧からセッションを見つけ、同じコードを入力します。"),
        ("Edits flow both ways as you make them.",
         "編集はその場で双方向に反映されます。"),
        ("Joining replaces the joiner's world with the host's, including their undo history — so join before you start building, not after.",
         "参加すると、参加した側のワールドはホストのもので置き換わります。取り消し履歴も一緒に消えるので、作り始める前に参加してください。"),
        ("Everything stays on your network. Nothing is uploaded anywhere.",
         "すべてネットワーク内で完結します。どこにもアップロードされません。"),

        // 10. Before you share it
        ("Before you share it", "人に渡す前に"),
        ("A short list that catches most of what makes a map unplayable.",
         "マップが遊べなくなる原因のほとんどは、この短いリストで見つかります。"),
        ("At least one Spawn part. Without it players have nowhere to start.",
         "スタート地点を最低1つ。ないとプレイヤーが始められません。"),
        ("Studio flags this for you — a world with no spawn point is reported as a problem before a session starts.",
         "これはStudioが教えてくれます。スタート地点のないワールドは、セッション開始前に問題として報告されます。"),
        ("A checkpoint before anything that can kill, or a mistake costs the whole run.",
         "死ぬ可能性がある場所の手前にはチェックポイントを。ないと1回のミスで最初からやり直しになります。"),
        ("No part scaled to zero on any axis. It becomes invisible but still blocks players.",
         "どの軸も大きさ0のパーツを残さないこと。見えないのに、プレイヤーを止めてしまいます。"),
        ("Walk the whole route in Play mode once, start to finish, without using the editor.",
         "プレイモードで、編集を使わずに最初から最後まで一度通してみます。"),
        ("Give the world a name you will recognise in the list a month from now.",
         "1か月後に一覧で見ても分かる名前を付けておきます。"),
    ]

    // MARK: - The published game catalogue

    static let catalogueEntries: [(String, String)] = [
        ("Games", "ゲーム"),
        ("Game", "ゲーム"),
        ("Unknown", "不明"),
        ("Downloaded", "ダウンロード済み"),
        ("Search games", "ゲームを検索"),
        ("by {}", "作者: {}"),
        ("Parts", "パーツ数"),
        ("Updated", "更新日"),
        ("Download and play", "ダウンロードして遊ぶ"),
        ("Host for friends", "友だちにホストする"),
        ("No games yet", "まだゲームがありません"),
        ("Checking for new games…", "新しいゲームを確認しています…"),
        ("Worlds people have published. Download one and play it on your own, or host it for friends.",
         "みんなが公開したワールドです。ダウンロードしてひとりで遊ぶことも、ホストして友だちを呼ぶこともできます。"),
        ("Games appear here once someone publishes one. Ablox Studio can prepare yours.",
         "誰かが公開するとここに並びます。Ablox Studioで自分のものを用意できます。"),
        ("Showing the games saved on this iPad.", "このiPadに保存済みのゲームを表示しています。"),
        ("Could not reach the game list.", "ゲーム一覧に接続できませんでした。"),
        ("Auto", "自動"),
        ("High", "高"),
        ("Low", "低"),
        ("Graphics", "グラフィック"),
        ("Show frame rate", "フレームレートを表示"),
        ("A small counter at the top of the screen while you play.", "遊んでいるあいだ、画面の上に小さく表示します。"),
        ("Lowers the quality by itself when the game gets slow, to stay above 30 fps.",
         "動きが重くなったら自動で画質を下げて、30fps以上をたもちます。"),
        ("Shadows, smooth shapes and everything in view. For newer iPads.",
         "影あり・なめらかな形・遠くまで表示。新しめのiPad向け。"),
        ("Shorter shadows, simpler shapes and a slightly lower resolution.",
         "影は近くだけ・形をシンプルに・解像度を少し下げます。"),
        ("No shadows, simple shapes, far parts hidden and a lower resolution. For big worlds and older iPads.",
         "影なし・シンプルな形・遠くのパーツを表示しない・解像度を下げる。大きなワールドや古いiPad向け。"),
        ("There is no game list on the branch “{}” of {}. Check the repository and branch in Settings.",
         "ブランチ「{}」（{}）にゲーム一覧がありません。設定のリポジトリとブランチを確認してください。"),
        ("Could not download “{}”.", "「{}」をダウンロードできませんでした。"),
        ("That game's listing is malformed.", "そのゲームの登録情報が壊れています。"),
        ("That world has too many parts to open safely.", "そのワールドはパーツが多すぎて安全に開けません。"),
        ("That catalogue address is not a GitHub repository.",
         "そのカタログのアドレスはGitHubリポジトリではありません。"),
        ("That download was too big and was refused.", "ダウンロードが大きすぎたため中止しました。"),
        ("That game list is too long and was refused.", "ゲーム一覧が長すぎたため読み込みませんでした。"),
        ("That game list could not be read.", "ゲーム一覧を読み込めませんでした。"),
        ("Part of that game list was malformed and was skipped.",
         "ゲーム一覧の一部が壊れていたので読み飛ばしました。"),
        ("That world was made with a newer version of Ablox Studio.",
         "そのワールドは新しいバージョンのAblox Studioで作られています。"),
        ("This game list needs a newer version of Ablox (list {}, this app reads {}).",
         "このゲーム一覧には新しいバージョンのAbloxが必要です（一覧 {}、このアプリ {}）。"),
        ("The listing says {} parts but the world has {}.",
         "登録では{}パーツですが、実際は{}パーツです。"),
        ("Game list", "ゲーム一覧"),
        ("Only worlds are downloaded, and only from this repository. Nothing is uploaded.",
         "ダウンロードされるのはワールドだけで、このリポジトリからのみです。アップロードは一切ありません。"),
        ("That is not a repository name. Using the built-in list.",
         "リポジトリ名として読めません。標準の一覧を使います。"),
        ("Which GitHub repository the Games tab reads.", "「ゲーム」タブが読むGitHubリポジトリです。"),
        ("Publish", "公開する"),
        ("Title", "タイトル"),
        ("Folder", "フォルダ"),
        ("obstacle, race, easy", "アスレチック, レース, かんたん"),
        ("Drawn from the world, looking straight down. Start, goal, checkpoints and hazards are picked out.",
         "ワールドを真上から見た図です。スタート・ゴール・チェックポイント・危険ブロックが強調されます。"),
        ("What to make", "作るもの"),
        ("What to fix", "直すところ"),
        ("AI World", "AIワールド"),
        ("Could not save that world.", "そのワールドを保存できませんでした。"),
        ("Publish this world", "このワールドを公開する"),
        ("Prepare for publishing", "公開の準備をする"),
        ("Cover image", "カバー画像"),
        ("Summary", "説明"),
        // "Tags" is already translated in the Inspector section above.
        ("Export files", "ファイルを書き出す"),
        ("Copy listing", "登録情報をコピー"),
        ("Copied", "コピーしました"),
        ("Open the games repository", "ゲームのリポジトリを開く"),
        ("What happens next", "このあとの手順"),
        ("Studio writes three files. Add them to the games repository with a pull request, and the game appears in Ablox for everyone.",
         "Studioが3つのファイルを書き出します。それをプルリクエストでゲームのリポジトリに追加すると、みんなのAbloxにそのゲームが出てきます。"),
        ("Pick a picture", "画像を選ぶ"),
        ("A wide picture works best — it is shown as a card.",
         "横長の画像が向いています。カードとして表示されます。"),
        ("The id is taken from the title and must be unique in the repository.",
         "IDはタイトルから作られ、リポジトリ内で重複しないようにします。"),
        ("Give the world a title before publishing it.", "公開する前にワールドのタイトルを付けてください。"),

        // Making a map with an assistant
        ("Make with AI", "AIで作る"),
        ("Make a map with AI", "AIでマップを作る"),
        ("Studio writes the prompt. Paste it into whichever assistant you use, then paste the answer back.",
         "Studioがプロンプトを書きます。使っているAIに貼り付けて、返ってきた答えをここに貼り戻してください。"),
        ("Nothing is sent from this iPad. You carry the text across yourself.",
         "このiPadからは何も送信されません。文章はあなたが自分で運びます。"),
        ("Theme", "テーマ"),
        ("a floating ruin, a lava cave, a candy town…", "空に浮かぶ遺跡、溶岩の洞窟、お菓子の町…"),
        ("Size", "大きさ"),
        ("Difficulty", "難しさ"),
        ("Coins", "コイン"),
        ("Hazards", "危険ブロック"),
        ("Gimmicks", "ギミック"),
        ("Copy the prompt", "プロンプトをコピー"),
        ("Paste the answer", "答えを貼り付ける"),
        ("Paste the JSON the assistant replied with", "AIが返したJSONを貼り付けてください"),
        ("Import", "読み込む"),
        ("Copy what to fix", "直してほしい内容をコピー"),
        ("Imported {} parts.", "{}個のパーツを読み込みました。"),
        ("Small", "小"),
        ("Medium", "中"),
        ("Large", "大"),
        ("Gentle", "やさしい"),
        ("Normal", "ふつう"),
        ("Hard", "むずかしい"),

        // The prompt itself
        ("You are designing a level for Ablox, a block-building game on iPad.",
         "あなたは、iPad向けのブロック建築ゲーム「Ablox」のレベルを設計します。"),
        ("Reply with one JSON object and nothing else — no explanation, no code fence.",
         "返答はJSONオブジェクト1つだけにしてください。説明もコードフェンスも不要です。"),
        ("## What to make", "## 作るもの"),
        ("## Format", "## 形式"),
        ("## The world", "## 世界のきまり"),
        ("## What a player can do", "## プレイヤーにできること"),
        ("## Rules", "## ルール"),
        ("Theme: {}", "テーマ: {}"),
        ("About {} parts.", "パーツは{}個ぐらい。"),
        ("Difficulty: {}.", "難しさ: {}。"),
        ("The player walks from a start pad to a goal. Make that route obvious.",
         "プレイヤーはスタート地点からゴールまで進みます。その道筋が分かるように作ってください。"),
        ("`kind` must be one of: {}", "`kind` は次のいずれかです: {}"),
        ("`behavior` is optional and must be one of: {}", "`behavior` は省略可で、次のいずれかです: {}"),
        ("`color` is optional, as #RRGGBB. `width`, `height`, `depth` and `yaw` are optional too.",
         "`color` は省略可で #RRGGBB 形式です。`width`・`height`・`depth`・`yaw` も省略できます。"),
        ("Coordinates are metres. Y is up. The floor is at y = 0 and is 40 by 40.",
         "座標の単位はメートルで、Yが上方向です。床は y = 0 にあり、40×40の広さです。"),
        ("A part's x, y and z are its centre, so a 1 m tall block resting on the floor has y = 0.5.",
         "パーツの x, y, z は中心の位置です。高さ1mのブロックを床に置くなら y = 0.5 になります。"),
        ("Keep everything within 100 m of the origin.", "すべて原点から100m以内に収めてください。"),
        ("A jump rises {} m. Never make a step taller than that.",
         "ジャンプで上がれる高さは{}mです。それより高い段差は作らないでください。"),
        ("A running jump crosses {} m at the very most.",
         "走りジャンプで越えられる距離は、最大でも{}mです。"),
        ("Keep gaps to {} m or less, so the jump does not have to be perfect.",
         "隙間は{}m以下にしてください。ぴったりのジャンプを要求しないためです。"),
        ("Players fall off the edge, so put a floor or a platform under every route.",
         "プレイヤーは端から落ちます。通り道の下には必ず床か足場を置いてください。"),
        ("Exactly one part with behavior \"spawn\". Put it on the floor.",
         "behavior が \"spawn\" のパーツをちょうど1つ、床の上に置いてください。"),
        ("Exactly one part with behavior \"goal\", at the end of the route.",
         "behavior が \"goal\" のパーツをちょうど1つ、道筋の終わりに置いてください。"),
        ("Every part must be reachable from the spawn.",
         "すべてのパーツはスタート地点からたどり着ける場所に置いてください。"),
        ("Do not overlap parts. Two blocks in the same place look like one broken block.",
         "パーツを重ねないでください。同じ場所に2つあると、壊れた1つのブロックに見えます。"),
        ("Put a few \"orb\" parts along the route, slightly off the easy path.",
         "道筋に沿って \"orb\" をいくつか、少しだけ寄り道した場所に置いてください。"),
        ("Use \"hazard\" parts to make the route risky.",
         "\"hazard\" を使って道筋に危険をつくってください。"),
        ("Put a \"checkpoint\" part before each hazard, or a mistake costs the whole run.",
         "危険の手前には必ず \"checkpoint\" を置いてください。ないと1回のミスで最初からやり直しになります。"),
        ("You may use behavior \"bounce\", \"disappear\" or \"teleport\" on ordinary parts.",
         "ふつうのパーツに behavior として \"bounce\"・\"disappear\"・\"teleport\" を使ってかまいません。"),
        ("A \"bounce\" part launches the player upward — use it to reach a height a jump cannot.",
         "\"bounce\" はプレイヤーを上に打ち上げます。ジャンプでは届かない高さに使ってください。"),
        ("That did not import. Fix these and send the whole JSON again:",
         "読み込めませんでした。次を直して、JSON全体をもう一度送ってください:"),

        // Importing what came back
        ("Part {}: {}", "パーツ{}: {}"),
        ("That is too much text to read.", "文章が長すぎて読み込めません。"),
        ("No JSON found. Paste the whole block, including the braces.",
         "JSONが見つかりません。波かっこを含めて全体を貼り付けてください。"),
        ("A part is missing “{}”.", "あるパーツに「{}」がありません。"),
        ("“{}” is the wrong type — numbers must not be in quotes.",
         "「{}」の型が違います。数値を引用符で囲まないでください。"),
        ("That JSON could not be read.", "そのJSONを読み込めませんでした。"),
        ("The plan has no parts in it.", "パーツが1つも入っていません。"),
        ("The plan has {} parts. The limit is {}.", "パーツが{}個あります。上限は{}個です。"),
        ("No spawn point was given, so one was added at the centre.",
         "スタート地点がなかったので、中央に1つ追加しました。"),
        ("“{}” is not a part. Use one of: {}", "「{}」というパーツはありません。次のいずれかを使ってください: {}"),
        ("“{}” is not a behaviour. Use one of: {}",
         "「{}」というふるまいはありません。次のいずれかを使ってください: {}"),
        ("“{}” is not a colour. Use #RRGGBB.", "「{}」は色として読めません。#RRGGBB の形式にしてください。"),
        ("{} is {}, which is off the map. Keep coordinates within ±{}.",
         "{} が {} で、マップの外です。座標は ±{} 以内にしてください。"),
        ("A size of {} is not usable. Sizes run from {} to {}.",
         "大きさ {} は使えません。{}から{}の範囲にしてください。"),
        ("The rotation is not a number.", "回転の値が数値ではありません。"),
    ]

    // MARK: - AbloxScript

    /// The script language's errors, the game API's errors, the shooter HUD,
    /// Studio's script editor and its reference. Errors are read by children
    /// in the middle of writing a game, so the Japanese says what to do in the
    /// plainest words that are still accurate.
    static let scriptEntries: [(String, String)] = [
        // Saved game data
        ("“save” needs a name first, like p.save(\"coins\", 10).", "「save」には名前が必要です。例: p.save(\"coins\", 10)"),
        ("That is too much to save (the limit is {} KB).", "保存するデータが大きすぎます（{} KB まで）。"),
        ("Saved lists and maps can only go {} deep.", "保存するリストやマップは {} 段までです。"),
        ("Only a real number can be saved.", "保存できるのはふつうの数だけです。"),
        ("Only numbers, text, true/false, lists and maps can be saved — not {}.", "保存できるのは数・文字・true/false・リスト・マップだけです（{} は保存できません）。"),
        ("A player's saved data has arrived. Read p.saved here.", "プレイヤーのセーブデータがとどいた。ここで p.saved を読む。"),
        ("Keeps something on the player's iPad for next time, reads it back, or forgets it. p.saved is nil until on loaded.",
         "次のためにプレイヤーのiPadに保存する・読み出す・消す。on loaded までは p.saved は nil。"),
        // Reading a script
        ("Line {}: {}", "{}行目: {}"),
        ("The script is too long.", "スクリプトが長すぎます。"),
        ("“{}” is not a number.", "「{}」は数として読めません。"),
        ("A text value was never closed with a quote.", "文字の値が引用符 \" で閉じられていません。"),
        ("“{}” cannot be used here.", "「{}」はここでは使えません。"),
        ("This is nested too deeply.", "入れ子が深すぎます。"),
        ("The script ends in the middle of something.", "何かの途中でスクリプトが終わっています。"),
        ("The “if” on line {} is never closed with “end”.", "{}行目の「if」が「end」で閉じられていません。"),
        ("The “for” on line {} is never closed with “end”.", "{}行目の「for」が「end」で閉じられていません。"),
        ("The “while” on line {} is never closed with “end”.", "{}行目の「while」が「end」で閉じられていません。"),
        ("The “func” on line {} is never closed with “end”.", "{}行目の「func」が「end」で閉じられていません。"),
        ("The “on” on line {} is never closed with “end”.", "{}行目の「on」が「end」で閉じられていません。"),
        ("The “{}” on this line is never closed with “end”.", "この行の「{}」が「end」で閉じられていません。"),
        ("There is already an “on {}” on line {}. Put both parts in one.",
         "「on {}」は{}行目にもうあります。1つにまとめてください。"),
        ("There is an extra “{}” here, or something above it is missing.",
         "ここに余分な「{}」があるか、その上で何かが足りません。"),
        ("To compare two things, use “==”, not “=”.", "2つを比べるときは「=」ではなく「==」を使います。"),
        ("This line does nothing. Did you mean to use “=” or call something?",
         "この行は何もしていません。「=」で代入するか、何かを呼び出すつもりでしたか？"),
        ("“{}” is a reserved word and cannot be used as a name.", "「{}」は予約語なので、名前には使えません。"),
        ("“{}” is listed twice.", "「{}」が2回書かれています。"),
        ("“let” needs a name after it.", "「let」のあとに名前が必要です。"),
        ("“func” needs a name after it.", "「func」のあとに名前が必要です。"),
        ("A function needs “(” after its name, even with nothing inside.",
         "関数の名前のあとには、中身がなくても「(」が必要です。"),
        ("Expected a parameter name.", "引数の名前が必要です。"),
        ("Expected “)” after the parameters.", "引数のあとに「)」が必要です。"),
        ("Expected “)” to close the call.", "呼び出しを閉じる「)」が必要です。"),
        ("Expected “)”.", "「)」が必要です。"),
        ("Expected “]” to close the list.", "リストを閉じる「]」が必要です。"),
        ("Expected “]”.", "「]」が必要です。"),
        ("Expected “}” to close the map.", "マップを閉じる「}」が必要です。"),
        ("Expected “:” after “{}”.", "「{}」のあとに「:」が必要です。"),
        ("Expected a name after “.”.", "「.」のあとに名前が必要です。"),
        ("Expected a name inside “{ }”.", "「{ }」の中に名前が必要です。"),
        ("“if” needs “then” after its condition.", "「if」の条件のあとに「then」が必要です。"),
        ("“elif” needs “then” after its condition.", "「elif」の条件のあとに「then」が必要です。"),
        ("“while” needs “do” after its condition.", "「while」の条件のあとに「do」が必要です。"),
        ("“for” needs a name, as in “for i in 1 to 10 do”.", "「for」には名前が必要です（例:「for i in 1 to 10 do」）。"),
        ("“for” needs “in”, as in “for i in 1 to 10 do”.", "「for」には「in」が必要です（例:「for i in 1 to 10 do」）。"),
        ("“for” needs “do” before its body.", "「for」の中身の前に「do」が必要です。"),
        ("“on” needs an event name, as in “on start()”.", "「on」にはイベント名が必要です（例:「on start()」）。"),
        ("“on” can only be used at the top of a script.", "「on」はスクリプトのいちばん外側でしか使えません。"),
        ("The left side of “=” has to be a name.", "「=」の左側は名前でなければなりません。"),

        // Running a script
        ("This took too long and was stopped. Is there a loop that never ends?",
         "時間がかかりすぎたので止めました。終わらないループはありませんか？"),
        ("Functions called each other too deeply. Does “{}” call itself forever?",
         "関数の呼び出しが深すぎます。「{}」が自分自身を永遠に呼んでいませんか？"),
        ("“break” can only be used inside a loop.", "「break」はループの中でしか使えません。"),
        ("“continue” can only be used inside a loop.", "「continue」はループの中でしか使えません。"),
        ("“return” can only be used inside a function or an “on”.", "「return」は関数か「on」の中でしか使えません。"),
        ("“step” cannot be 0 — the loop would never end.", "「step」を0にはできません。ループが終わらなくなります。"),
        ("“for … in” needs a list, a map or text, not {}.", "「for … in」にはリスト・マップ・文字が必要です（{}は使えません）。"),
        ("“{}” is not defined.", "「{}」はまだ作られていません。"),
        ("“{}” is not defined. Did you mean “{}”?", "「{}」はまだ作られていません。「{}」のことですか？"),
        ("“{}” is not defined. Use “let {} = …” to make it first.",
         "「{}」はまだ作られていません。先に「let {} = …」で作ってください。"),
        ("“{}” cannot be changed here.", "「{}」はここでは変えられません。"),
        ("This is nil, so it has no “{}” to set.", "これは nil なので、「{}」を設定できません。"),
        ("This is nil, so it has no “{}”.", "これは nil なので、「{}」はありません。"),
        ("“{}” is nil, so it has no “{}”.", "「{}」は nil なので、「{}」はありません。"),
        ("“{}” is nil, not a function.", "「{}」は nil で、関数ではありません。"),
        ("A {} has no “{}” to set.", "{}には設定できる「{}」がありません。"),
        ("A {} has no “{}”.", "{}には「{}」がありません。"),
        ("A {} cannot be indexed with a {}.", "{}を{}で番号指定することはできません。"),
        ("A {} cannot be called like a function.", "{}は関数のように呼び出せません。"),
        ("There is no item {} — the list has {}. Use append() to add one.",
         "{}番目はありません（リストは{}個）。追加するときは append() を使います。"),
        ("Cannot divide by zero.", "0で割ることはできません。"),
        ("Cannot compare a {} with a {}.", "{}と{}は比べられません。"),
        ("“{}” needs a number here, not {}.", "「{}」にはここで数が必要です（{}ではなく）。"),
        ("That text is too long.", "その文字は長すぎます。"),
        ("That list or map is too big (the limit is {}).", "そのリストかマップは大きすぎます（上限は{}）。"),
        ("“{}” needs {} values.", "「{}」には値が{}個必要です。"),
        ("“{}” needs a list first.", "「{}」の最初にはリストが必要です。"),

        // The game API
        ("“on {}” never happens. Did you mean “on {}”?", "「on {}」は起こりません。「on {}」のことですか？"),
        ("“on {}” never happens. The events are: {}.", "「on {}」は起こりません。使えるイベント: {}。"),
        ("Round over", "ラウンド終了"),
        ("“{}” is a function. Call it with ().", "「{}」は関数です。() を付けて呼び出してください。"),
        ("That number is too big.", "その数は大きすぎます。"),
        ("A block has no “{}”.", "ブロックには「{}」がありません。"),
        ("A block’s “{}” cannot be set.", "ブロックの「{}」は変えられません。"),
        ("“game” has no “{}”.", "「game」には「{}」がありません。"),
        ("“game.{}” cannot be set.", "「game.{}」は変えられません。"),
        ("There is no sound called “{}”. The sounds are: {}.", "「{}」という音はありません。使える音: {}。"),
        ("That needs a player, a block or a position like {x: 0, y: 5, z: 0}, not {}.",
         "ここにはプレイヤー、ブロック、または {x: 0, y: 5, z: 0} のような位置が必要です（{}ではなく）。"),
        ("“{}” is not a colour. Try “red”, “blue” or “#FF8800”.", "「{}」は色として読めません。「red」「青」「#FF8800」などにしてください。"),
        ("“{}” needs a function to run, like func() … end.", "「{}」には実行する関数が必要です（func() … end のように）。"),
        ("Too many timers at once (the limit is {}). Is “{}” inside “on tick”?",
         "タイマーが多すぎます（上限は{}）。「{}」を「on tick」の中に書いていませんか？"),
        ("A weapon needs a name.", "武器には名前が必要です。"),
        ("Too many weapons (the limit is {}).", "武器が多すぎます（上限は{}）。"),
        ("A weapon has no “{}”. It can have: {}.", "武器に「{}」はありません。使えるもの: {}。"),
        ("There is no weapon called “{}”. The weapons are: {}.", "「{}」という武器はありません。使える武器: {}。"),
        ("A bar’s maximum has to be more than 0.", "バーの最大値は0より大きくしてください。"),
        ("“at” is one of: {}.", "「at」に使えるのは: {}。"),
        ("A screen item has no “{}”. It can have: {}.", "画面の項目に「{}」はありません。使えるもの: {}。"),
        ("Too many things on the screen (the limit is {}).", "画面の項目が多すぎます（上限は{}）。"),

        // Sounds a script can play
        ("Shoot", "発射"),
        ("Hit", "命中"),
        ("Reload", "リロード"),
        ("Defeated", "やられた"),

        // Playing a scripted game
        ("Knocked out", "やられた！"),
        ("You'll be back in a moment.", "まもなく復活します。"),
        ("Health {} of {}", "体力 {} / {}"),
        ("Reloading", "リロード中"),
        ("{} of {} rounds", "残り{}発（{}発中）"),
        ("Fire", "撃つ"),
        ("Script", "スクリプト"),
        ("Dismiss", "閉じる"),
        ("Codes never contain O, 0, I, 1, L or U.", "コードには O・0・I・1・L・U は使われません。"),

        // Studio's script editor
        ("Start from an example", "サンプルから始める"),
        ("{} lines", "{}行"),
        ("No problems found", "問題は見つかりませんでした"),
        ("{} problems", "問題が{}件"),
        ("No script yet", "スクリプトはまだありません"),
        ("Check", "チェック"),
        ("Test run", "テスト実行"),
        ("Examples", "サンプル"),
        ("Reference", "リファレンス"),
        ("Test run: two players, nobody pressing anything", "テスト実行: プレイヤー2人、操作なし"),
        ("It ran without errors, but did nothing anyone could see.", "エラーなく動きましたが、目に見えることは何も起きませんでした。"),
        ("You", "あなた"),
        ("Guest", "ゲスト"),
        ("Weapon: {}", "武器: {}"),
        ("Health: {} / {}", "体力: {} / {}"),
        ("Speed ×{}, jump ×{}", "速さ ×{}、ジャンプ ×{}"),
        ("On screen: {}", "画面の文字: {}"),
        ("Bar “{}”: {} / {}", "バー「{}」: {} / {}"),
        ("Button: {}", "ボタン: {}"),
        ("Message: {}", "メッセージ: {}"),
        ("The round ended after {} seconds.", "{}秒でラウンドが終わりました。"),

        // Samples
        ("1v1 shooter", "1対1シューティング"),
        ("First person, a rifle each, first to 5 knockouts wins.", "1人称でライフルを持って対戦。先に5回倒した方の勝ち。"),
        ("1v1 shooter: first to 5 knockouts wins.", "1対1シューティング: 先に5回倒した方の勝ち。"),
        ("Look through their eyes and hand them a rifle.", "プレイヤーの目線にして、ライフルを渡す。"),
        ("Team battle", "チーム戦"),
        ("Red against blue, taking turns as people join. Teammates can't hurt each other.",
         "入った順に赤と青に分かれて対戦。味方同士では攻撃が当たりません。"),
        ("Team battle: the first team to 10 knockouts wins.", "チーム戦: 先に10回倒したチームの勝ち。"),
        ("Odd players are red, even players are blue.", "奇数番目のプレイヤーは赤、偶数番目は青。"),

        // The reference
        ("The language", "言語の基本"),
        ("Makes a variable. Use it again without “let”.", "変数を作ります。2回目からは「let」なしで使います。"),
        ("Does something only when it is true.", "条件が正しいときだけ実行します。"),
        ("Counts. “for x in list do” goes through a list.", "数を数えます。「for x in list do」でリストを順に使えます。"),
        ("Repeats while something is true.", "条件が正しいあいだ繰り返します。"),
        ("Makes your own function.", "自分の関数を作ります。"),
        ("A list (starts at 1) and a map.", "リスト（1番から始まる）とマップ。"),
        ("A comment. The game ignores it.", "コメント。ゲームには無視されます。"),
        ("Events", "イベント"),
        ("The round begins.", "ラウンドが始まったとき。"),
        ("Ten times a second. dt is the time since the last one.", "1秒に10回。dt は前回からの秒数。"),
        ("A player arrives. Give them a weapon or a camera here.", "プレイヤーが入ったとき。ここで武器やカメラを設定します。"),
        ("A player leaves.", "プレイヤーが抜けたとき。"),
        ("A player taps a block.", "プレイヤーがブロックをタップしたとき。"),
        ("A shot hits someone. Return a number to change the damage.", "弾が誰かに当たったとき。数を return するとダメージを変えられます。"),
        ("A shot hits a block.", "弾がブロックに当たったとき。"),
        ("Someone is knocked out. killer is nil if nobody did it.", "誰かが倒されたとき。誰のせいでもなければ killer は nil。"),
        ("A knocked-out player comes back.", "倒されたプレイヤーが復活したとき。"),
        ("A player presses a screen button.", "プレイヤーが画面のボタンを押したとき。"),
        ("Everyone", "全員"),
        ("A button. Pressing it runs “on button”.", "ボタン。押すと「on button」が動きます。"),
        ("Makes a new weapon. Anything left out comes from the model.", "新しい武器を作ります。書かなかった値は model の武器と同じになります。"),
        ("Seconds before a knocked-out player returns. -1: only when you call respawn().",
         "倒されてから復活するまでの秒数。-1 なら respawn() を呼んだときだけ復活。"),
        ("Lets teammates hurt each other.", "味方同士でも攻撃が当たるようにします。"),
        ("A player (p)", "プレイヤー (p)"),
        ("Health. Setting health to 0 knocks them out.", "体力。health を0にすると倒れます。"),
        ("Weapons: blaster, rifle, shotgun, pistol, or your own.", "武器: blaster、rifle、shotgun、pistol、または自分で作った武器。"),
        ("Store your own values on a player.", "プレイヤーに自分の値を保存できます。"),
        ("Handy extras", "便利な機能"),
        ("Runs something once, later.", "少しあとに1回だけ実行します。"),
        ("Runs something again and again, until cancelled.", "止めるまで何度も繰り返し実行します。"),
        ("Seconds since the round began.", "ラウンドが始まってからの秒数。"),
        ("Metres between two players, blocks or positions.", "2つのプレイヤー・ブロック・位置のあいだの距離（メートル）。"),
        ("A random number, a dice roll, or a random item.", "ランダムな数、サイコロ、またはリストからランダムに1つ。"),
        ("Shows a value in the Test run console.", "テスト実行の結果に値を表示します。"),
        ("Working with lists.", "リストの操作。"),
        ("Maps and text.", "マップと文字の操作。"),
        ("Converting between numbers and text.", "数と文字の変換。"),
        ("More text and list helpers.", "文字とリストのその他の便利機能。"),
        // .absc files and the wider API
        ("{}, line {}: {}", "{} の {}行目: {}"),
        ("A screen item needs a short name first, like ui_text(\"score\", …).",
         "画面の項目には、最初に短い名前が必要です（ui_text(\"score\", …) のように）。"),
        ("A character’s “{}” cannot be set directly.", "キャラクターの「{}」は直接は変えられません。"),
        ("Too many values stored on one character.", "1人のキャラクターに保存した値が多すぎます。"),
        ("Only an NPC can “{}”.", "「{}」はNPCにしか使えません。"),
        ("Too many NPCs (the limit is {}).", "NPCが多すぎます（上限は{}）。"),
        ("“camera” is one of: {}.", "「camera」に使えるのは: {}。"),
        ("“hat” is one of: {}.", "「hat」に使えるのは: {}。"),
        ("“ride” is one of: {}.", "「ride」に使えるのは: {}。"),
        ("Draws them riding something: none, car, sports, truck, kart, bike, scooter, jetpack, hoverboard. Only the look — set speed too.",
         "乗り物に乗った見た目にする: none, car, sports, truck, kart, bike, scooter, jetpack, hoverboard。見た目だけなので、速さは speed で。"),
        ("“behavior” is one of: {}.", "「behavior」に使えるのは: {}。"),
        ("What touching it does: trigger, hazard, checkpoint, bounce, collectible and more. Only a block with a behavior reports “on touch”.",
         "触れたときの動き: trigger（すり抜けて反応）、hazard、checkpoint、bounce、collectible など。behavior があるブロックだけが「on touch」で反応します。"),
        ("“material” is one of: {}.", "「material」に使えるのは: {}。"),
        ("“shape” is one of: {}.", "「shape」に使えるのは: {}。"),
        ("“pivot” is one of: {}.", "「pivot」に使えるのは: {}。"),
        ("“size” is a number, or “small”, “medium”, “large” or “huge”.",
         "「size」は数、または「small」「medium」「large」「huge」のどれかです。"),
        ("“tags” needs a list, like [\"coin\"].", "「tags」にはリストが必要です（[\"coin\"] のように）。"),
        ("“world” has no “{}”.", "「world」には「{}」がありません。"),
        ("“world.{}” cannot be set.", "「world.{}」は変えられません。"),
        ("The world has too many blocks (the limit is {}).", "ワールドのブロックが多すぎます（上限は{}）。"),
        ("There is no screen item called “{}”.", "「{}」という画面の項目はありません。"),
        ("A screen item has no “{}”.", "画面の項目には「{}」がありません。"),
        ("This needs options in { }, like {x: 0.5, y: 0.1}.", "ここには { } で囲んだ設定が必要です（{x: 0.5, y: 0.1} のように）。"),
        ("That needs {x, y, z}, not {}.", "ここには {x, y, z} が必要です（{}ではなく）。"),

        // Test run
        ("Camera: {}", "カメラ: {}"),
        ("The joystick or the top bar is hidden.", "ジョイスティックか上のバーが隠れています。"),
        ("Screen item: {}", "画面の項目: {}"),
        ("NPCs: {}", "NPC: {}体"),
        ("Blocks created: {}", "作られたブロック: {}個"),

        // Studio's file list
        ("New file", "新しいファイル"),
        ("Export .absc", ".absc を書き出す"),
        ("Share or save to Files", "共有・「ファイル」に保存"),
        ("That file could not be written.", "そのファイルを書き出せませんでした。"),
        ("Rename file", "ファイル名を変える"),
        ("File name", "ファイル名"),
        ("Switch off", "オフにする"),
        ("Switch on", "オンにする"),
        ("{} files", "{}個のファイル"),
        ("A world can have up to {} script files.", "1つのワールドに入れられるスクリプトは{}個までです。"),
        ("Those files could not be opened.", "そのファイルを開けませんでした。"),
        ("“{}” is not a text file.", "「{}」はテキストファイルではありません。"),
        ("Scripts make the games rules can't: shooters, menus, NPCs, maps that change, anything.",
         "スクリプトなら、ルールではできないゲームが作れます。シューティング、メニュー、NPC、変化するマップ、なんでも。"),

        // Samples
        ("Zombie waves", "ゾンビウェーブ"),
        ("Zombies chase the nearest player. Each wave brings more, and tougher.",
         "ゾンビがいちばん近いプレイヤーを追いかけてくる。ウェーブごとに数も強さも増えていく。"),
        ("Zombie waves: survive as long as you can.", "ゾンビウェーブ: できるだけ長く生き残ろう。"),
        ("Zombies appear in a ring around the middle of the map.", "ゾンビはマップの中心を囲むように現れる。"),
        ("Title screen and shop", "タイトル画面とショップ"),
        ("A title screen with a Play button, coins over time, and a shop that sells speed and jump.",
         "プレイボタンのあるタイトル画面、時間でたまるコイン、速さとジャンプを売るショップ。"),
        ("A title screen first: no joystick until Play is pressed.", "最初はタイトル画面: プレイを押すまでジョイスティックは出ない。"),
        ("One coin every two seconds.", "2秒ごとにコイン1枚。"),
        ("Obstacle course builder", "障害物コース自動生成"),
        ("Builds its own staircase in the sky with a moving step, and times every run.",
         "空に階段と動く足場を自分で作り、ゴールまでのタイムを計る。"),
        ("Builds its own obstacle course, then times each run.", "障害物コースを自動で作り、1回ごとのタイムを計る。"),
        ("Step 6 slides back and forth forever.", "6段目はずっと行ったり来たりする。"),

        // The reference
        ("Positions add, subtract and multiply like arrows.", "位置は矢印のように足し算・引き算・かけ算ができます。"),
        ("A world can have many .absc files. They run together; each can have its own “on join”.",
         "1つのワールドに .absc ファイルをいくつも入れられます。全部いっしょに動き、それぞれに「on join」を書けます。"),
        ("A player or NPC touches a block.", "プレイヤーかNPCがブロックに触れたとき。"),
        ("Someone fires.", "誰かが撃ったとき。"),
        ("A player sends text from a text box.", "プレイヤーがテキストボックスから文字を送ったとき。"),
        ("A player says something in the chat — commands, passwords, quizzes.",
         "プレイヤーがチャットに書いたとき。コマンド、合言葉、クイズなどに。"),
        ("Everyone in the game, the NPCs, or one player by name.", "ゲームにいる全員、NPC全員、または名前で1人。"),
        ("A message, a chat line or a sound for everyone.", "全員へのメッセージ、チャット、音。"),
        ("Fades or shakes everyone's screen.", "全員の画面をフェードしたり揺らしたりします。"),
        ("Ends the round, or starts it again from the beginning.", "ラウンドを終わらせる、または最初からやり直す。"),
        ("Seconds since the round began, and whether it has ended.", "ラウンド開始からの秒数と、終わったかどうか。"),
        ("Who they are. Name, score and team can be changed.", "だれか。名前・点数・チームは変更できます。"),
        ("Where they are and which way they face. Set position to teleport, yaw to turn, velocity to launch.",
         "いる場所と向き。position で瞬間移動、yaw で向きを変え、velocity で飛ばせます。"),
        ("Moves them to a block, a player or {x, y, z}; throws them; turns them to face something.",
         "ブロック・プレイヤー・{x, y, z} へ移動、投げ飛ばす、何かの方を向かせる。"),
        ("How they look, for everyone. size 0.2 to 10; hats: none, cap, crown, antenna, halo.",
         "見た目（全員に見えます）。size は0.2〜10、帽子: none, cap, crown, antenna, halo。"),
        ("How they move, up to 10 times. frozen stops them moving.", "動き方。最大10倍。frozen で動けなくなります。"),
        ("First person, behind them, looking down from above, or fixed in place.",
         "1人称、後ろから、真上から見下ろす、または決まった場所に固定。"),
        ("How far the camera is, how wide it sees, or a fixed camera looking at something.",
         "カメラの距離、見える広さ、または何かを映す固定カメラ。"),
        ("Hides the joystick and buttons, or the top bar and chat.", "ジョイスティックとボタン、または上のバーとチャットを隠します。"),
        ("Fades or shakes this player's screen.", "このプレイヤーの画面をフェードしたり揺らしたりします。"),
        ("Hurt, heal, knock out, or bring back.", "ダメージ、回復、倒す、復活させる。"),
        ("A message, chat line or sound for this player only.", "このプレイヤーだけへのメッセージ、チャット、音。"),
        ("NPCs", "NPC（ゲームが動かすキャラ）"),
        ("Makes a character the game controls. It has everything a player has.",
         "ゲームが動かすキャラクターを作ります。プレイヤーと同じことが全部できます。"),
        ("Walks somewhere, keeps following someone, or stops.", "どこかへ歩く、誰かを追いかけ続ける、または止まる。"),
        ("Jumps, fires its weapon at someone, or speaks in a bubble over its head.", "ジャンプする、誰かを撃つ、頭の上のふきだしでしゃべる。"),
        ("Removes it. A knocked-out NPC is removed unless “on death” brings it back.",
         "消します。倒されたNPCは「on death」で復活させない限り消えます。"),
        ("Screen GUI", "画面GUI"),
        ("Text on everyone's screen. Call again with the same id to change it.", "全員の画面に文字を出します。同じ id でもう一度呼ぶと書き換わります。"),
        ("A box. Put things inside it with {parent: \"menu\"}; hiding or removing it takes them too.",
         "箱（パネル）。{parent: \"menu\"} で中に入れられ、隠したり消したりすると中身もいっしょです。"),
        ("An icon (any SF Symbol name) or a bar.", "アイコン（SF Symbolの名前）またはバー。"),
        ("A text box. Sending it runs “on input”.", "テキストボックス。送信すると「on input」が動きます。"),
        ("Changes, removes or clears screen items.", "画面の項目を変える・消す・全部消す。"),
        ("Every ui_ function returns the item, so you can change it directly.", "ui_ の関数は項目を返すので、それを直接変えられます。"),
        ("The same, on one player's screen only.", "同じことを、1人のプレイヤーの画面だけに。"),
        ("Options. x and y go from 0 to 1 across the screen (or the panel); at: top_left, top, center, bottom_right, …",
         "設定。x と y は画面（またはパネル）の端から端まで0〜1。at: top_left, top, center, bottom_right など。"),
        ("Blocks and the world", "ブロックとワールド"),
        ("One block by name, every block with a tag, or every block.", "名前で1つ、タグの付いたもの全部、またはブロック全部。"),
        ("Makes a new block. Shapes: box, sphere, cylinder, cone, plane.", "新しいブロックを作ります。形: box, sphere, cylinder, cone, plane。"),
        ("Where it is and what it looks like. All can be changed.", "場所と見た目。全部変えられます。"),
        ("Hide it, let players walk through it, rename or retag it.", "隠す、すり抜けられるようにする、名前やタグを変える。"),
        ("Moves it by x, y, z (or to something) over some seconds, or turns it.", "x, y, z だけ（または何かの所まで）数秒かけて動かす、または回す。"),
        ("Copies it, or removes it.", "コピーする、または消す。"),
        ("The sky and the light.", "空と明るさ。"),
        ("Gravity (-9.81 is normal), the sun, the ground plane and the height you fall out of the world.",
         "重力（-9.81 がふつう）、太陽、地面、ワールドから落ちたとみなす高さ。"),
        ("The first thing along a line: {point, distance, block, player}, or nil.", "線の先で最初に当たるもの: {point, distance, block, player}、なければ nil。"),
        ("Working with positions and directions.", "位置や方向の計算。"),
        ("More list tools. sort, map and filter take a function.", "リストの便利な道具。sort、map、filter には関数を渡します。"),
        ("Maths. Angles are in degrees.", "計算。角度は度です。"),

        // Getting .absc files from GitHub, and published games in Studio.
        ("Added {}", "追加: {}"),
        ("Updated {}", "更新: {}"),
        ("Skipped {} (too many files)", "{} は入れられませんでした（ファイルが多すぎます）"),
        ("Already up to date.", "もう最新です。"),
        ("That path is not a folder in the repository.", "その場所はリポジトリのフォルダではありません。"),
        ("GitHub's answer could not be read.", "GitHubからの返事が読めませんでした。"),
        ("That repository, branch or folder is not valid.", "リポジトリ・ブランチ・フォルダのどれかが正しくありません。"),
        ("Nothing was found there. Check the repository, the branch and the folder, and that the repository is public.",
         "そこには何もありませんでした。リポジトリ・ブランチ・フォルダの名前と、リポジトリが公開（Public）になっているかを確かめてください。"),
        ("GitHub is limiting requests from this network. Try again in a few minutes.",
         "このネットワークからのGitHubへの問い合わせが多すぎます。数分たってからもう一度試してください。"),
        ("GitHub answered with an error ({}).", "GitHubがエラーを返しました（{}）。"),
        ("Could not reach GitHub.", "GitHubにつながりませんでした。"),
        ("Could not get the latest scripts, so the saved ones are used: {}",
         "最新のスクリプトを取得できなかったので、保存されているものを使います: {}"),
        ("Scripts updated from GitHub: {}", "GitHubからスクリプトを取得しました: {}"),
        ("That is not a branch name. Using main.", "ブランチ名として使えません。main を使います。"),
        ("From GitHub", "GitHubから取得"),
        ("GitHub settings", "GitHubの設定"),
        ("The latest files are fetched every time the game starts.", "ゲームを始めるたびに最新のファイルを取得します。"),
        ("Get the latest now", "今すぐ最新を取得"),
        ("No .absc files were found there.", "そこに .absc ファイルが見つかりませんでした。"),
        ("Get .absc files from GitHub", "GitHubから .absc を取得"),
        ("Scripts from GitHub", "GitHubのスクリプト"),
        ("Write .absc files on a computer, push them to a public GitHub repository, and bring them into this world with one tap.",
         "パソコンで .absc を書いて公開（Public）のGitHubリポジトリに置けば、ボタン1つでこのワールドに取り込めます。"),
        ("Repository", "リポジトリ"),
        ("Branch", "ブランチ"),
        ("Folder (empty for the top)", "フォルダ（いちばん上なら空のまま）"),
        ("Get the latest every time the game starts", "遊ぶたびに最新を取得する"),
        ("The host fetches the files again before each game, so a fix pushed to GitHub reaches everyone without publishing again. If GitHub cannot be reached, the saved files are used.",
         "ゲームを始める前にホストがもう一度ファイルを取得するので、GitHubに直したものを置けば公開し直さなくても全員に届きます。GitHubにつながらないときは保存されているファイルを使います。"),
        ("Files with the same name are replaced. Files that are only on this iPad are kept.",
         "同じ名前のファイルは置き換わります。このiPadにしかないファイルは消えません。"),
        ("Only reads public repositories. Nothing is uploaded.", "公開リポジトリを読むだけです。何もアップロードしません。"),
        ("Save and get files", "保存して取得"),
        ("Stop getting files from GitHub", "GitHubからの取得をやめる"),
        ("Open a published game", "公開ゲームを開く"),
        ("Open in Studio", "Studioで開く"),
        ("No games here yet", "ここにはまだゲームがありません"),
        ("Check the repository and the branch, then tap Reload.", "リポジトリとブランチを確かめて、「リロード」を押してください。"),
        ("Loading the game list…", "ゲーム一覧を読み込み中…"),
        ("Ablox uses the same list and branch on this iPad.", "このiPadの Ablox も同じ一覧とブランチを使います。"),
        ("{} script files", "スクリプト {} 個"),
    ]
}
